<?php
require_once __DIR__ . '/../../../cors.php';
require_once __DIR__ . '/../../../db/db.php';
require_once __DIR__ . '/../../../reusables/organization_rbac.php';
header('Content-Type: application/json');
$ctx=requireOrganizationAccess($pdo,'hr.members.update');
if(($_SERVER['REQUEST_METHOD']??'GET')!=='POST')organizationJsonError(405,'Method not allowed.');
$data=json_decode(file_get_contents('php://input'),true)?:[];$memberId=(int)($data['organization_member_id']??0);$status=strtolower(trim((string)($data['membership_status']??'')));$note=trim(strip_tags((string)($data['note']??'')));
if($memberId<=0)organizationJsonError(422,'A valid organization member is required.');if(!in_array($status,['active','inactive','terminated'],true))organizationJsonError(422,'Choose active, inactive, or terminated.');if($status!=='active'&&mb_strlen($note)<5)organizationJsonError(422,'Please provide a short reason for restricting this member.');
try{$stmt=$pdo->prepare("SELECT om.id,om.user_id,om.membership_status,ur.role AS account_role FROM organization_members om INNER JOIN user_roles ur ON ur.user_id=om.user_id WHERE om.id=? AND om.organization_id=? AND om.deleted_at IS NULL LIMIT 1");$stmt->execute([$memberId,$ctx['organization_id']]);$member=$stmt->fetch(PDO::FETCH_ASSOC);if(!$member)organizationJsonError(404,'Organization member not found.');if($member['account_role']==='organization_admin')organizationJsonError(409,'The primary Organization Admin cannot be deactivated here.');if((int)$member['user_id']===(int)$ctx['user_id'])organizationJsonError(409,'You cannot change your own membership status.');if($member['membership_status']===$status)organizationJsonError(409,'This member is already in that status.');$pdo->beginTransaction();$pdo->prepare('UPDATE organization_members SET membership_status=?,updated_at=NOW() WHERE id=?')->execute([$status,$memberId]);if($status!=='active')$pdo->prepare("UPDATE personnel_profiles SET availability_status='unavailable',updated_at=NOW() WHERE organization_member_id=?")->execute([$memberId]);logOrganizationRbac($pdo,$ctx,'organization_members',$memberId,'update',['membership_status'=>$member['membership_status']],['membership_status'=>$status,'note'=>$note?:null]);$pdo->commit();echo json_encode(['success'=>true,'message'=>$status==='active'?'Employee access reactivated.':($status==='inactive'?'Employee access paused.':'Employee membership terminated.')]);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('Organization member status update failed: '.$e->getMessage());organizationJsonError(500,'Unable to update this employee.');}
