<?php
require_once __DIR__ . '/../../../cors.php';
require_once __DIR__ . '/../../../db/db.php';
require_once __DIR__ . '/../../../reusables/organization_rbac.php';
header('Content-Type: application/json');
$ctx=requireOrganizationAccess($pdo,'hr.availability.update');
if(($_SERVER['REQUEST_METHOD']??'GET')!=='POST')organizationJsonError(405,'Method not allowed.');
$data=json_decode(file_get_contents('php://input'),true)?:[];$memberId=(int)($data['organization_member_id']??0);$status=strtolower(trim((string)($data['availability_status']??'')));$note=trim(strip_tags((string)($data['note']??'')));
$allowed=['available','assigned','off_duty','leave','unavailable'];if($memberId<=0)organizationJsonError(422,'A valid organization member is required.');if(!in_array($status,$allowed,true))organizationJsonError(422,'Invalid availability status.');
try{$stmt=$pdo->prepare("SELECT om.id,om.membership_status,COALESCE(pp.availability_status,'off_duty') AS availability_status FROM organization_members om LEFT JOIN personnel_profiles pp ON pp.organization_member_id=om.id WHERE om.id=? AND om.organization_id=? AND om.deleted_at IS NULL LIMIT 1");$stmt->execute([$memberId,$ctx['organization_id']]);$member=$stmt->fetch(PDO::FETCH_ASSOC);if(!$member)organizationJsonError(404,'Organization member not found.');if($ctx['user_role']!=='organization_admin' && $memberId!==(int)$ctx['organization_member_id'] && !organizationHasPermission($pdo,$ctx,'hr.members.update'))organizationJsonError(403,'You may only update your own availability.');if($member['membership_status']!=='active')organizationJsonError(409,'Only active employees can be marked available for duty.');$old=$member['availability_status'];$pdo->beginTransaction();$exists=$pdo->prepare('SELECT id FROM personnel_profiles WHERE organization_member_id=?');$exists->execute([$memberId]);if($exists->fetchColumn())$pdo->prepare('UPDATE personnel_profiles SET availability_status=?,updated_at=NOW() WHERE organization_member_id=?')->execute([$status,$memberId]);else$pdo->prepare('INSERT INTO personnel_profiles (organization_member_id,availability_status) VALUES (?,?)')->execute([$memberId,$status]);$pdo->prepare('INSERT INTO personnel_availability_logs (organization_member_id,old_status,new_status,changed_by_user_id,notes) VALUES (?,?,?,?,?)')->execute([$memberId,$old,$status,$ctx['user_id'],$note?:null]);logOrganizationRbac($pdo,$ctx,'personnel_profiles',$memberId,'update',['availability_status'=>$old],['availability_status'=>$status,'note'=>$note?:null]);$pdo->commit();echo json_encode(['success'=>true,'message'=>'Duty availability updated.']);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('Personnel availability update failed: '.$e->getMessage());organizationJsonError(500,'Unable to update duty availability.');}
