<template><PageShell title="Compliance Review" subtitle="Review organization documents and ambulance credential alerts across the city." icon="lucide:file-check-2" eyebrow="Platform Executive">
  <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card label="Organizations" :value="stats.organizations" icon="lucide:building-2"/><Card label="Pending documents" :value="stats.pending_documents" icon="lucide:files"/><Card label="Rejected documents" :value="stats.rejected_documents" icon="lucide:file-x-2"/><Card label="Credential alerts" :value="stats.credential_alerts" icon="lucide:badge-alert"/></div>
  <div class="mt-6 grid gap-6 xl:grid-cols-[1.05fr_.95fr]">
    <section class="rounded-3xl border border-base-300 bg-base-100 p-5 shadow-sm dark:border-white/10 dark:bg-[#071829]"><h2 class="text-lg font-black dark:text-white">Organization compliance</h2><div v-if="loading" class="py-12 text-center text-sm text-slate-400">Loading compliance...</div><div v-else class="mt-4 space-y-3"><article v-for="o in organizations" :key="o.id" class="rounded-2xl bg-base-200 p-4 dark:bg-white/[.035]"><div class="flex items-start justify-between gap-3"><div><p class="font-black text-slate-800 dark:text-white/75">{{ o.name }}</p><p class="mt-1 text-xs text-slate-400">{{ o.docs_total }} documents · {{ o.fleet_total }} fleet units</p></div><span class="rounded-full px-2.5 py-1 text-[.65rem] font-black" :class="o.docs_pending>0||o.docs_rejected>0||o.expired_units>0?'bg-amber-100 text-amber-700':'bg-emerald-100 text-emerald-700'">{{ o.docs_pending>0||o.docs_rejected>0||o.expired_units>0?'Needs attention':'Clear' }}</span></div><div class="mt-3 grid grid-cols-3 gap-2 text-center"><Mini label="Pending" :value="o.docs_pending"/><Mini label="Rejected" :value="o.docs_rejected"/><Mini label="Expired units" :value="o.expired_units"/></div></article></div></section>
    <section class="rounded-3xl border border-base-300 bg-base-100 p-5 shadow-sm dark:border-white/10 dark:bg-[#071829]"><h2 class="text-lg font-black dark:text-white">Credential alerts</h2><div v-if="!alerts.length && !loading" class="py-12 text-center text-sm text-slate-400">No ambulance credential alerts within 30 days.</div><div class="mt-4 space-y-3"><article v-for="a in alerts" :key="a.id" class="rounded-2xl border border-amber-200 bg-amber-50/60 p-4 dark:border-amber-500/20 dark:bg-amber-500/10"><p class="font-black text-slate-800 dark:text-white/75">{{ a.unit_code }} · {{ a.plate_number }}</p><p class="mt-1 text-xs text-slate-500 dark:text-white/45">{{ a.organization_name }}</p><p class="mt-2 text-xs font-bold text-amber-700 dark:text-amber-300">Registration: {{ a.registration_expiry||'Not recorded' }} · Inspection: {{ a.inspection_expiry||'Not recorded' }}</p></article></div></section>
  </div>
</PageShell></template>
<script setup>
import { defineComponent,h,onMounted,ref } from 'vue';import { Icon } from '@iconify/vue';import PageShell from '@/components/management/PageShell.vue';import { fetchPlatformCompliance } from '@/services/adminCompletion'
const loading=ref(false),stats=ref({}),organizations=ref([]),alerts=ref([])
const Card=defineComponent({props:{label:String,value:[String,Number],icon:String},setup:p=>()=>h('article',{class:'rounded-3xl border border-base-300 bg-base-100 p-5 shadow-sm dark:border-white/10 dark:bg-[#071829]'},[h(Icon,{icon:p.icon,width:20,class:'text-red-500'}),h('p',{class:'mt-4 text-2xl font-black dark:text-white'},String(p.value??0)),h('p',{class:'mt-1 text-xs font-bold text-slate-500'},p.label)])});const Mini=defineComponent({props:{label:String,value:[String,Number]},setup:p=>()=>h('div',{class:'rounded-xl bg-base-100 p-2 dark:bg-white/5'},[h('p',{class:'text-sm font-black dark:text-white'},String(p.value??0)),h('p',{class:'text-[.6rem] uppercase text-slate-400'},p.label)])})
onMounted(async()=>{loading.value=true;try{const d=await fetchPlatformCompliance();stats.value=d.stats||{};organizations.value=d.organizations||[];alerts.value=d.credential_alerts||[]}finally{loading.value=false}})
</script>
