<template>
  <section class="min-h-screen bg-base-200 px-4 py-6 sm:px-6 lg:px-8"><div class="mx-auto max-w-[1450px] space-y-5">
    <header><p class="text-[.68rem] font-black uppercase tracking-[.16em] text-red-600">Incidents & Care</p><h1 class="mt-1 text-3xl font-black tracking-tight text-slate-950 dark:text-white">Facility Handoffs</h1><p class="mt-2 max-w-3xl text-sm text-slate-500 dark:text-white/45">Create a limited receiving-facility endorsement and record the facility response and physical handoff.</p></header>
    <div class="grid gap-5 xl:grid-cols-[340px_minmax(0,1fr)]">
      <aside class="rounded-3xl border border-base-300 bg-base-100 p-3 shadow-sm dark:border-white/10 dark:bg-[#0d2943]"><p class="px-2 pb-3 text-xs font-black uppercase tracking-[.12em] text-slate-400">Mission</p><button v-for="m in missions" :key="m.id" class="mb-1 w-full rounded-2xl border p-3 text-left" :class="selected?.id===m.id?'border-red-200 bg-red-50 dark:border-red-500/20 dark:bg-red-500/10':'border-transparent hover:bg-base-200 dark:hover:bg-white/[.03]'" @click="selectedId=m.id"><p class="text-sm font-black text-slate-900 dark:text-white">{{m.reference_number}}</p><p class="mt-1 text-xs text-slate-500 dark:text-white/45">{{m.unit_code}} · {{pretty(m.assignment_status)}}</p></button><div v-if="!missions.length" class="p-8 text-center text-sm text-slate-400">No mission records yet.</div></aside>
      <main v-if="selected" class="space-y-5">
        <section class="rounded-3xl border border-base-300 bg-base-100 p-5 shadow-sm dark:border-white/10 dark:bg-[#0d2943] sm:p-6">
          <div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 class="text-lg font-black text-slate-950 dark:text-white">Receiving facility · {{selected.reference_number}}</h2><p class="mt-1 text-xs text-slate-400">Create an endorsement once responders are on scene.</p></div><span class="rounded-full bg-red-50 px-2.5 py-1 text-[.62rem] font-black uppercase text-red-700 dark:bg-red-500/10 dark:text-red-300">{{pretty(selected.assignment_status)}}</span></div>
          <div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="block sm:col-span-2"><span class="label">Receiving facility</span><select v-model="form.medical_facility_id" class="input"><option value="">Select facility</option><option v-for="f in facilities" :key="f.id" :value="f.id">{{f.name}} · {{f.address_text}}</option></select></label><label class="block"><span class="label">Estimated arrival (minutes)</span><input v-model="form.eta_minutes" type="number" min="0" max="360" class="input"/></label><label class="block"><span class="label">Endorsement note</span><input v-model="form.notes" class="input" placeholder="Patient condition / heads-up"/></label></div><div class="mt-5 flex justify-end"><button :disabled="saving || !canCreate" class="rounded-xl bg-red-600 px-5 py-2.5 text-xs font-black text-white disabled:opacity-50" @click="create"><Icon icon="lucide:send" width="14" class="mr-1 inline"/>Create Endorsement</button></div>
          <p v-if="!canCreate" class="mt-3 text-xs font-semibold text-amber-700">A handoff can be created when the mission is On Scene or Transporting and no other handoff is currently active.</p>
        </section>
        <section class="rounded-3xl border border-base-300 bg-base-100 p-5 shadow-sm dark:border-white/10 dark:bg-[#0d2943] sm:p-6"><h2 class="text-sm font-black text-slate-900 dark:text-white">Handoff history</h2><div class="mt-4 space-y-3"><article v-for="h in handoffs" :key="h.id" class="rounded-2xl border border-base-300 bg-base-200/35 p-4 dark:border-white/10 dark:bg-white/[.03]"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-sm font-black text-slate-800 dark:text-white/70">{{h.facility_name}}</p><p class="mt-1 text-xs text-slate-400">{{h.facility_address}}</p></div><span class="rounded-full px-2.5 py-1 text-[.6rem] font-black uppercase" :class="statusClass(h.status)">{{pretty(h.status)}}</span></div><div class="mt-3 grid gap-2 text-xs sm:grid-cols-3"><Info label="ETA" :value="h.eta_minutes!=null?`${h.eta_minutes} min`:'—'"/><Info label="Created" :value="formatDate(h.created_at)"/><Info label="Initiated by" :value="h.initiated_by"/></div><p v-if="h.notes" class="mt-3 rounded-xl bg-base-100 p-3 text-xs text-slate-500 dark:bg-white/5 dark:text-white/45">{{h.notes}}</p><div v-if="h.status==='pending'" class="mt-4 flex flex-wrap gap-2"><button class="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-black text-white" @click="change(h,'accepted')">Record Facility Accepted</button><button class="rounded-xl border border-red-200 bg-red-50 px-3 py-2 text-xs font-black text-red-700" @click="change(h,'declined')">Record Facility Declined</button></div><div v-if="h.status==='accepted'" class="mt-4"><button class="rounded-xl bg-red-600 px-3 py-2 text-xs font-black text-white" @click="change(h,'completed')"><Icon icon="lucide:handshake" width="14" class="mr-1 inline"/>Confirm Physical Handoff</button></div></article><div v-if="!handoffs.length" class="rounded-2xl border border-dashed border-base-300 p-8 text-center text-sm text-slate-400 dark:border-white/10">No facility handoff has been created for this mission.</div></div></section>
      </main><div v-else class="grid min-h-[500px] place-items-center rounded-3xl border border-dashed border-base-300 bg-base-100 p-10 text-center text-sm font-bold text-slate-400 dark:border-white/10 dark:bg-[#0d2943]">Choose a mission to coordinate a receiving facility.</div>
    </div>
  </div></section>
</template>
<script setup>
import { computed, defineComponent, h, onMounted, ref, watch } from 'vue'
import { Icon } from '@iconify/vue'
import { fetchOrganizationMissions } from '@/services/dispatchOperations'
import { createHandoff, fetchHandoffs, fetchReceivingFacilities, updateHandoffStatus } from '@/services/rescueOperations'
import { useAlert } from '@/composables/useAlert'
const alert=useAlert(),missions=ref([]),facilities=ref([]),handoffs=ref([]),selectedId=ref(null),saving=ref(false),form=ref({medical_facility_id:'',eta_minutes:15,notes:''})
const selected=computed(()=>missions.value.find(m=>m.id===selectedId.value)||missions.value[0]||null);const hasActive=computed(()=>handoffs.value.some(h=>['pending','accepted'].includes(h.status)));const canCreate=computed(()=>selected.value&&['on_scene','transporting'].includes(selected.value.assignment_status)&&!hasActive.value)
const pretty=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());const formatDate=v=>v?new Date(String(v).replace(' ','T')).toLocaleString():'—';const statusClass=s=>({pending:'bg-amber-50 text-amber-700',accepted:'bg-blue-50 text-blue-700',declined:'bg-red-50 text-red-700',completed:'bg-emerald-50 text-emerald-700'}[s]||'bg-base-200 text-slate-500')
const Info=defineComponent({props:{label:String,value:[String,Number]},setup(p){return()=>h('div',{class:'rounded-xl bg-base-100 px-3 py-2 dark:bg-white/5'},[h('p',{class:'text-[.58rem] font-black uppercase tracking-wide text-slate-400'},p.label),h('p',{class:'mt-1 font-semibold text-slate-700 dark:text-white/55'},p.value||'—')])}})
async function load(){try{const [m,f]=await Promise.all([fetchOrganizationMissions(),fetchReceivingFacilities()]);missions.value=m.missions||[];facilities.value=f.facilities||[];if(!selectedId.value)selectedId.value=missions.value[0]?.id||null}catch(e){alert.error(e?.response?.data?.message||e.message||'Unable to load handoff workspace.')}}
async function loadHandoffs(){if(!selected.value){handoffs.value=[];return}try{const d=await fetchHandoffs(selected.value.id);handoffs.value=d.handoffs||[]}catch(e){alert.error(e?.response?.data?.message||e.message||'Unable to load handoffs.')}}
async function create(){if(!selected.value)return;saving.value=true;try{const d=await createHandoff({assignment_id:selected.value.id,medical_facility_id:Number(form.value.medical_facility_id),eta_minutes:Number(form.value.eta_minutes||0),notes:form.value.notes});alert.success(d.message);form.value={medical_facility_id:'',eta_minutes:15,notes:''};await loadHandoffs()}catch(e){alert.error(e?.response?.data?.message||e.message||'Unable to create handoff.')}finally{saving.value=false}}
async function change(h,status){const ok=await alert.confirm(`${pretty(status)} this facility handoff?`,'Update handoff');if(!ok)return;try{const d=await updateHandoffStatus(h.id,status);alert.success(d.message);await loadHandoffs()}catch(e){alert.error(e?.response?.data?.message||e.message||'Unable to update handoff.')}}
watch(selectedId,loadHandoffs);onMounted(async()=>{await load();await loadHandoffs()})
</script>
<style scoped>.label{margin-bottom:.4rem;display:block;font-size:.65rem;font-weight:900;text-transform:uppercase;letter-spacing:.1em;color:#94a3b8}.input{width:100%;border:1px solid hsl(var(--bc)/.12);background:hsl(var(--b1));border-radius:.75rem;padding:.7rem .8rem;font-size:.8rem;outline:none}.input:focus{border-color:#dc2626;box-shadow:0 0 0 3px rgba(220,38,38,.08)}</style>
