<template>
  <section class="min-h-screen bg-base-200 px-4 py-6 sm:px-6 lg:px-8"><div class="mx-auto max-w-[1380px] space-y-5">
    <header><p class="text-[.68rem] font-black uppercase tracking-[.16em] text-red-600">Incidents & Care</p><h1 class="mt-1 text-3xl font-black tracking-tight text-slate-950 dark:text-white">Field Reports</h1><p class="mt-2 max-w-3xl text-sm text-slate-500 dark:text-white/45">Document the incident response, actions taken, and outcome. Keep this focused on the current incident.</p></header>
    <div class="grid gap-5 xl:grid-cols-[340px_minmax(0,1fr)]">
      <aside class="rounded-3xl border border-base-300 bg-base-100 p-3 shadow-sm dark:border-white/10 dark:bg-[#0d2943]"><p class="px-2 pb-3 text-xs font-black uppercase tracking-[.12em] text-slate-400">Mission</p><button v-for="m in missions" :key="m.id" class="mb-1 w-full rounded-2xl border p-3 text-left" :class="selected?.id===m.id?'border-red-200 bg-red-50 dark:border-red-500/20 dark:bg-red-500/10':'border-transparent hover:bg-base-200 dark:hover:bg-white/[.03]'" @click="selectedId=m.id"><p class="text-sm font-black text-slate-900 dark:text-white">{{m.reference_number}}</p><p class="mt-1 text-xs text-slate-500 dark:text-white/45">{{m.category_name}} · {{pretty(m.assignment_status)}}</p></button><div v-if="!missions.length" class="p-8 text-center text-sm text-slate-400">No mission records yet.</div></aside>
      <main v-if="selected" class="rounded-3xl border border-base-300 bg-base-100 p-5 shadow-sm dark:border-white/10 dark:bg-[#0d2943] sm:p-6">
        <div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 class="text-lg font-black text-slate-950 dark:text-white">{{selected.reference_number}}</h2><p class="mt-1 text-xs text-slate-400">{{selected.address_text}}</p></div><span v-if="report?.report_status" class="rounded-full bg-base-200 px-2.5 py-1 text-[.62rem] font-black uppercase text-slate-600 dark:bg-white/5 dark:text-white/55">{{pretty(report.report_status)}}</span></div>
        <div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="block sm:col-span-2"><span class="label">Incident summary</span><textarea v-model="form.incident_summary" class="input min-h-28" placeholder="What responders found on scene"></textarea></label><label class="block sm:col-span-2"><span class="label">Actions taken</span><textarea v-model="form.actions_taken" class="input min-h-28" placeholder="Response actions / interventions / transport actions"></textarea></label><label class="block"><span class="label">Outcome</span><select v-model="form.outcome" class="input"><option value="treated_on_scene">Treated on scene</option><option value="transported">Transported</option><option value="refused_transport">Refused transport</option><option value="no_patient_found">No patient found</option><option value="deceased">Deceased</option><option value="other">Other</option></select></label><label class="block"><span class="label">Destination facility</span><select v-model="form.destination_facility_id" class="input"><option value="">None / not transported</option><option v-for="f in facilities" :key="f.id" :value="f.id">{{f.name}}</option></select></label></div>
        <div class="mt-5 flex flex-wrap justify-end gap-2"><button :disabled="saving" class="rounded-xl border border-base-300 bg-base-100 px-4 py-2.5 text-xs font-black text-slate-700 hover:bg-base-200 dark:border-white/10 dark:bg-white/5 dark:text-white/60" @click="save(false)"><Icon icon="lucide:save" width="14" class="mr-1 inline"/>Save Draft</button><button :disabled="saving" class="rounded-xl bg-red-600 px-4 py-2.5 text-xs font-black text-white hover:bg-red-700" @click="save(true)"><Icon icon="lucide:send" width="14" class="mr-1 inline"/>Submit Report</button></div>
        <div v-if="report" class="mt-5 rounded-2xl border border-base-300 bg-base-200/35 p-4 text-xs text-slate-500 dark:border-white/10 dark:bg-white/[.03] dark:text-white/45">Prepared by <strong>{{report.prepared_by}}</strong><span v-if="report.submitted_at"> · submitted {{formatDate(report.submitted_at)}}</span></div>
      </main><div v-else class="grid min-h-[500px] place-items-center rounded-3xl border border-dashed border-base-300 bg-base-100 p-10 text-center text-sm font-bold text-slate-400 dark:border-white/10 dark:bg-[#0d2943]">Choose a mission to open its field report.</div>
    </div>
  </div></section>
</template>
<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { Icon } from '@iconify/vue'
import { fetchOrganizationMissions } from '@/services/dispatchOperations'
import { fetchFieldReport, fetchReceivingFacilities, saveFieldReport } from '@/services/rescueOperations'
import { useAlert } from '@/composables/useAlert'
const alert=useAlert(),missions=ref([]),facilities=ref([]),selectedId=ref(null),report=ref(null),saving=ref(false),form=ref({incident_summary:'',actions_taken:'',outcome:'other',destination_facility_id:''})
const selected=computed(()=>missions.value.find(m=>m.id===selectedId.value)||missions.value[0]||null);const pretty=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());const formatDate=v=>v?new Date(String(v).replace(' ','T')).toLocaleString():'—'
async function load(){try{const [m,f]=await Promise.all([fetchOrganizationMissions(),fetchReceivingFacilities()]);missions.value=m.missions||[];facilities.value=f.facilities||[];if(!selectedId.value)selectedId.value=missions.value[0]?.id||null}catch(e){alert.error(e?.response?.data?.message||e.message||'Unable to load field reports.')}}
async function loadReport(){if(!selected.value){report.value=null;return}try{const d=await fetchFieldReport(selected.value.emergency_request_id);report.value=d.report||null;form.value={incident_summary:report.value?.incident_summary||'',actions_taken:report.value?.actions_taken||'',outcome:report.value?.outcome||'other',destination_facility_id:report.value?.destination_facility_id||''}}catch(e){alert.error(e?.response?.data?.message||e.message||'Unable to load field report.')}}
async function save(submit){if(!selected.value)return;saving.value=true;try{const d=await saveFieldReport({assignment_id:selected.value.id,...form.value,destination_facility_id:form.value.destination_facility_id?Number(form.value.destination_facility_id):null,submit});alert.success(d.message);await loadReport()}catch(e){alert.error(e?.response?.data?.message||e.message||'Unable to save report.')}finally{saving.value=false}}
watch(selectedId,loadReport);onMounted(async()=>{await load();await loadReport()})
</script>
<style scoped>.label{margin-bottom:.4rem;display:block;font-size:.65rem;font-weight:900;text-transform:uppercase;letter-spacing:.1em;color:#94a3b8}.input{width:100%;border:1px solid hsl(var(--bc)/.12);background:hsl(var(--b1));border-radius:.75rem;padding:.7rem .8rem;font-size:.8rem;outline:none}.input:focus{border-color:#dc2626;box-shadow:0 0 0 3px rgba(220,38,38,.08)}</style>
