<template>
  <section class="min-h-screen bg-base-200 px-4 py-6 sm:px-6 lg:px-8">
    <div class="mx-auto max-w-[1500px] space-y-5">
      <header class="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
        <div><p class="text-[.68rem] font-black uppercase tracking-[.16em] text-red-600">Dispatch</p><h1 class="mt-1 text-3xl font-black tracking-tight text-slate-950 dark:text-white">Resource Assignment</h1><p class="mt-2 max-w-3xl text-sm text-slate-500 dark:text-white/45">Turn an accepted incident into a real rescue mission by locking one dispatch-ready ambulance and an available response crew.</p></div>
        <button class="inline-flex items-center justify-center gap-2 rounded-xl border border-base-300 bg-base-100 px-4 py-2.5 text-sm font-bold text-slate-700 shadow-sm hover:bg-base-200 dark:border-white/10 dark:bg-[#0d2943] dark:text-white/65" @click="load"><Icon icon="lucide:refresh-cw" width="16" :class="loading?'animate-spin':''"/>Refresh</button>
      </header>

      <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Awaiting Assignment" :value="incidents.length" icon="lucide:inbox"/><Stat label="Ready Ambulances" :value="ambulances.length" icon="lucide:ambulance"/><Stat label="Available Personnel" :value="personnel.length" icon="lucide:users-round"/><Stat label="Recent Assignments" :value="recent.length" icon="lucide:route"/></div>

      <div v-if="loading" class="grid place-items-center rounded-3xl border border-base-300 bg-base-100 py-20 dark:border-white/10 dark:bg-[#0d2943]"><span class="h-8 w-8 animate-spin rounded-full border-2 border-red-600 border-t-transparent"></span></div>
      <div v-else-if="error" class="rounded-3xl border border-red-200 bg-red-50 p-8 text-center text-sm font-semibold text-red-700">{{ error }}</div>
      <template v-else>
        <div class="grid gap-5 xl:grid-cols-[390px_minmax(0,1fr)]">
          <aside class="overflow-hidden rounded-3xl border border-base-300 bg-base-100 shadow-sm dark:border-white/10 dark:bg-[#0d2943]">
            <div class="border-b border-base-300 p-4 dark:border-white/10"><h2 class="text-sm font-black text-slate-900 dark:text-white">Accepted Incidents</h2><p class="mt-1 text-xs text-slate-400">Select an incident ready for resource assignment.</p></div>
            <div class="max-h-[650px] overflow-y-auto p-2">
              <button v-for="incident in incidents" :key="incident.id" class="mb-1 w-full rounded-2xl border p-3 text-left transition" :class="selected?.id===incident.id?'border-red-200 bg-red-50 dark:border-red-500/20 dark:bg-red-500/10':'border-transparent hover:border-base-300 hover:bg-base-200 dark:hover:border-white/10 dark:hover:bg-white/[.03]'" @click="selectIncident(incident)"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><p class="truncate text-sm font-black text-slate-900 dark:text-white">{{ incident.reference_number }}</p><p class="mt-1 text-xs font-bold text-slate-600 dark:text-white/55">{{ incident.category_name }}</p><p class="mt-1 line-clamp-2 text-[.67rem] leading-5 text-slate-400">{{ incident.address_text }}</p></div><span class="rounded-full px-2 py-1 text-[.58rem] font-black uppercase" :class="severityClass(incident.severity)">{{ incident.severity }}</span></div></button>
              <div v-if="!incidents.length" class="p-8 text-center"><Icon icon="lucide:badge-check" width="26" class="mx-auto text-emerald-500"/><p class="mt-2 text-sm font-bold text-slate-500">No accepted incidents are waiting for resources.</p></div>
            </div>
          </aside>

          <main v-if="selected" class="rounded-3xl border border-base-300 bg-base-100 shadow-sm dark:border-white/10 dark:bg-[#0d2943]">
            <header class="border-b border-base-300 p-5 dark:border-white/10 sm:p-6"><div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div class="flex flex-wrap items-center gap-2"><h2 class="text-xl font-black text-slate-950 dark:text-white">{{ selected.reference_number }}</h2><span class="rounded-full bg-red-50 px-2.5 py-1 text-[.62rem] font-black uppercase text-red-700 dark:bg-red-500/10 dark:text-red-300">{{ selected.severity }}</span></div><p class="mt-2 text-sm text-slate-500 dark:text-white/45">{{ selected.category_name }} · {{ selected.address_text }}</p></div><div class="rounded-2xl bg-base-200 px-4 py-3 text-right"><p class="text-xl font-black text-slate-950 dark:text-white">{{ Number(selected.total_score||0).toFixed(1) }}</p><p class="text-[.6rem] font-bold uppercase tracking-wider text-slate-400">Accepted DSS score</p></div></div></header>

            <div class="space-y-6 p-5 sm:p-6">
              <section><div class="flex items-end justify-between gap-3"><div><h3 class="text-sm font-black text-slate-900 dark:text-white">1. Choose ambulance</h3><p class="mt-1 text-xs text-slate-400">Only currently ready and available units can be selected.</p></div></div><div class="mt-3 grid gap-2 md:grid-cols-2"><button v-for="unit in ambulances" :key="unit.id" class="rounded-2xl border p-3 text-left transition" :class="ambulanceId===unit.id?'border-red-300 bg-red-50 dark:border-red-500/30 dark:bg-red-500/10':'border-base-300 bg-base-200/40 hover:bg-base-200 dark:border-white/10 dark:bg-white/[.025]'" @click="ambulanceId=unit.id"><div class="flex items-center justify-between"><div><p class="text-sm font-black text-slate-800 dark:text-white/75">{{ unit.unit_code }}</p><p class="mt-1 text-[.66rem] text-slate-400">{{ unit.plate_number }} · {{ pretty(unit.ambulance_type) }}</p></div><span v-if="selected.recommended_ambulance_id===unit.id" class="rounded-full bg-blue-50 px-2 py-1 text-[.58rem] font-black text-blue-600 dark:bg-blue-500/10 dark:text-blue-300">DSS PICK</span></div></button><div v-if="!ambulances.length" class="col-span-full rounded-2xl border border-dashed border-base-300 p-6 text-center text-xs text-slate-400">No ambulance is dispatch-ready. Run readiness checks or resolve maintenance first.</div></div></section>

              <section><div class="flex items-end justify-between gap-3"><div><h3 class="text-sm font-black text-slate-900 dark:text-white">2. Assign response crew</h3><p class="mt-1 text-xs text-slate-400">Select exactly one driver plus at least one additional responder.</p></div><span class="rounded-full bg-base-200 px-3 py-1.5 text-[.63rem] font-bold text-slate-500">{{ selectedCrew.length }} selected</span></div>
                <div class="mt-3 max-h-[380px] space-y-2 overflow-y-auto pr-1"><article v-for="person in personnel" :key="person.organization_member_id" class="grid gap-3 rounded-2xl border border-base-300 bg-base-200/40 p-3 dark:border-white/10 dark:bg-white/[.025] sm:grid-cols-[auto_minmax(0,1fr)_180px] sm:items-center"><input :checked="isCrewSelected(person.organization_member_id)" type="checkbox" class="h-4 w-4 accent-red-600" @change="toggleCrew(person)"/><div class="min-w-0"><p class="truncate text-sm font-black text-slate-800 dark:text-white/75">{{ person.first_name }} {{ person.last_name }}</p><p class="mt-1 truncate text-[.65rem] text-slate-400">{{ person.role_names.join(', ') || 'Operational employee' }}<span v-if="person.license_number"> · {{ person.license_number }}</span></p></div><select v-if="isCrewSelected(person.organization_member_id)" v-model="crewRoleMap[person.organization_member_id]" class="field"><option value="driver">Driver</option><option value="team_leader">Team Leader</option><option value="emt">EMT</option><option value="paramedic">Paramedic</option><option value="rescuer">Rescuer</option></select><span v-else class="hidden text-right text-[.62rem] font-bold uppercase text-slate-300 sm:block">Available</span></article><div v-if="!personnel.length" class="rounded-2xl border border-dashed border-base-300 p-6 text-center text-xs text-slate-400">No personnel are currently marked Available.</div></div>
              </section>

              <div class="flex flex-col gap-3 rounded-2xl border border-base-300 bg-base-200/40 p-4 sm:flex-row sm:items-center sm:justify-between dark:border-white/10 dark:bg-white/[.025]"><div><p class="text-sm font-black text-slate-800 dark:text-white/70">Ready to create mission?</p><p class="mt-1 text-xs text-slate-400">Assignment immediately reserves the ambulance and marks selected crew as Assigned.</p></div><button :disabled="saving||!canSubmit" class="rounded-xl bg-red-600 px-5 py-2.5 text-sm font-bold text-white hover:bg-red-700 disabled:cursor-not-allowed disabled:opacity-40" @click="assign"><Icon v-if="saving" icon="lucide:loader-circle" width="15" class="mr-1 inline animate-spin"/>Assign Resources</button></div>
            </div>
          </main>

          <main v-else class="grid min-h-[480px] place-items-center rounded-3xl border border-dashed border-base-300 bg-base-100 p-10 text-center dark:border-white/10 dark:bg-[#0d2943]"><div><span class="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-base-200 text-slate-300"><Icon icon="lucide:git-pull-request-arrow" width="25"/></span><p class="mt-4 text-sm font-black text-slate-600 dark:text-white/50">Choose an accepted incident to assign resources.</p></div></main>
        </div>

        <section class="rounded-3xl border border-base-300 bg-base-100 shadow-sm dark:border-white/10 dark:bg-[#0d2943]"><div class="border-b border-base-300 px-5 py-4 dark:border-white/10"><h2 class="text-sm font-black text-slate-900 dark:text-white">Recent Assignments</h2></div><div v-if="!recent.length" class="p-8 text-center text-sm text-slate-400">No assignments yet.</div><div v-else class="divide-y divide-base-300 dark:divide-white/5"><div v-for="row in recent" :key="row.id" class="flex flex-col gap-2 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-sm font-black text-slate-800 dark:text-white/70">{{ row.reference_number }} · {{ row.unit_code }}</p><p class="mt-1 text-xs text-slate-400">{{ row.crew_count }} crew · {{ formatDate(row.assigned_at) }}</p></div><span class="rounded-full bg-base-200 px-2.5 py-1 text-[.62rem] font-black uppercase text-slate-500">{{ pretty(row.assignment_status) }}</span></div></div></section>
      </template>
    </div>
  </section>
</template>

<script setup>
import { computed, defineComponent, h, onMounted, ref } from 'vue'
import { Icon } from '@iconify/vue'
import { createResourceAssignment, fetchResourceAssignments } from '@/services/dispatchOperations'
import { useAlert } from '@/composables/useAlert'
const alert=useAlert();const loading=ref(false),error=ref(''),incidents=ref([]),ambulances=ref([]),personnel=ref([]),recent=ref([]),selectedId=ref(null),ambulanceId=ref(null),crewRoleMap=ref({}),saving=ref(false)
const selected=computed(()=>incidents.value.find(i=>i.id===selectedId.value)||incidents.value[0]||null)
const selectedCrew=computed(()=>Object.entries(crewRoleMap.value).filter(([,r])=>r).map(([id,crew_role])=>({organization_member_id:Number(id),crew_role})))
const canSubmit=computed(()=>ambulanceId.value&&selectedCrew.value.length>=2&&selectedCrew.value.filter(c=>c.crew_role==='driver').length===1)
const Stat=defineComponent({props:{label:String,value:[String,Number],icon:String},setup(p){return()=>h('article',{class:'rounded-2xl border border-base-300 bg-base-100 p-4 shadow-sm dark:border-white/10 dark:bg-[#0d2943]'},[h('div',{class:'flex items-center justify-between'},[h('div',{},[h('p',{class:'text-xs font-bold text-slate-400'},p.label),h('p',{class:'mt-1 text-2xl font-black text-slate-950 dark:text-white'},String(p.value??0))]),h('span',{class:'grid h-10 w-10 place-items-center rounded-xl bg-red-50 text-red-600 dark:bg-red-500/10 dark:text-red-300'},[h(Icon,{icon:p.icon,width:18})])])])}})
async function load(){loading.value=true;error.value='';try{const d=await fetchResourceAssignments();incidents.value=d.incidents||[];ambulances.value=d.ambulances||[];personnel.value=d.personnel||[];recent.value=d.recent_assignments||[];if(!selectedId.value||!incidents.value.some(i=>i.id===selectedId.value))selectedId.value=incidents.value[0]?.id||null;if(selected.value)selectIncident(selected.value)}catch(e){error.value=e?.response?.data?.message||e.message||'Unable to load assignments.'}finally{loading.value=false}}
function selectIncident(i){selectedId.value=i.id;ambulanceId.value=ambulances.value.some(a=>a.id===i.recommended_ambulance_id)?i.recommended_ambulance_id:(ambulances.value[0]?.id||null);crewRoleMap.value={}}
function isCrewSelected(id){return !!crewRoleMap.value[id]}
function suggestedRole(p){const r=p.role_names.map(x=>x.toLowerCase()).join(' ');if(r.includes('driver'))return'driver';if(r.includes('medic')||r.includes('emt'))return'emt';if(r.includes('supervisor'))return'team_leader';return'rescuer'}
function toggleCrew(p){const n={...crewRoleMap.value};if(n[p.organization_member_id])delete n[p.organization_member_id];else n[p.organization_member_id]=suggestedRole(p);crewRoleMap.value=n}
async function assign(){if(!selected.value||!canSubmit.value)return;const ok=await alert.confirm(`Assign the selected ambulance and ${selectedCrew.value.length} crew members to ${selected.value.reference_number}?`,'Create rescue mission');if(!ok)return;saving.value=true;try{const d=await createResourceAssignment({emergency_request_id:selected.value.id,ambulance_id:ambulanceId.value,crew:selectedCrew.value});alert.success(d.message);selectedId.value=null;await load()}catch(e){alert.error(e?.response?.data?.message||e.message||'Unable to assign resources.')}finally{saving.value=false}}
const pretty=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());const formatDate=v=>v?new Date(String(v).replace(' ','T')).toLocaleString():'—';function severityClass(v){return {critical:'bg-red-100 text-red-700 dark:bg-red-500/10 dark:text-red-300',high:'bg-orange-100 text-orange-700',moderate:'bg-amber-100 text-amber-700',low:'bg-emerald-100 text-emerald-700'}[v]||'bg-base-200 text-slate-500'}
onMounted(load)
</script>
<style scoped>.field{width:100%;border-radius:.75rem;border:1px solid var(--color-base-300);background:var(--color-base-100);padding:.55rem .7rem;font-size:.75rem;color:#334155;outline:none}:global([data-theme="dark"]) .field{border-color:rgba(255,255,255,.1);background:#071829;color:white}</style>
