<template>
  <section class="min-h-screen bg-base-200 px-4 py-6 sm:px-6 lg:px-8">
    <div class="mx-auto max-w-7xl space-y-5">
      <header class="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p class="text-[0.68rem] font-black uppercase tracking-[0.16em] text-red-600 dark:text-red-300">Dispatch</p><h1 class="mt-1 flex flex-wrap items-center gap-3 text-3xl font-black tracking-tight text-slate-950 dark:text-white">Incident Offers <LiveBadge :live="live" /></h1><p class="mt-2 max-w-2xl text-sm text-slate-500 dark:text-white/45">Respond to timed DSS recommendations. Accepting reserves organizational responsibility only; ambulance and crew assignment happens next.</p></div><button class="inline-flex items-center justify-center gap-2 rounded-xl border border-base-300 bg-base-100 px-4 py-2.5 text-sm font-bold text-slate-700 shadow-sm hover:bg-base-200 dark:border-white/10 dark:bg-[#0d2943] dark:text-white/70" @click="load"><Icon icon="lucide:refresh-cw" width="16" :class="loading ? 'animate-spin' : ''" />Refresh</button></header>

      <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article v-for="card in statCards" :key="card.label" class="rounded-2xl border border-base-300 bg-base-100 p-4 shadow-sm dark:border-white/10 dark:bg-[#0d2943]"><div class="flex items-center justify-between"><div><p class="text-xs font-bold text-slate-400">{{card.label}}</p><p class="mt-1 text-2xl font-black text-slate-950 dark:text-white">{{card.value}}</p></div><span class="grid h-10 w-10 place-items-center rounded-xl bg-red-50 text-red-600 dark:bg-red-500/10 dark:text-red-300"><Icon :icon="card.icon" width="18" /></span></div></article></div>

      <div v-if="loading" class="grid place-items-center rounded-3xl border border-base-300 bg-base-100 py-20 dark:border-white/10 dark:bg-[#0d2943]"><span class="h-8 w-8 animate-spin rounded-full border-2 border-red-600 border-t-transparent"></span></div>
      <div v-else-if="error" class="rounded-3xl border border-red-200 bg-red-50 p-10 text-center dark:border-red-500/20 dark:bg-red-500/10"><Icon icon="lucide:triangle-alert" width="24" class="mx-auto text-red-500"/><p class="mt-2 text-sm font-semibold text-red-700 dark:text-red-200">{{error}}</p></div>
      <template v-else>
        <section>
          <div class="mb-3 flex items-center justify-between"><h2 class="text-sm font-black uppercase tracking-wider text-slate-500 dark:text-white/45">Awaiting Response</h2><span class="text-xs text-slate-400">{{ activeOffers.length }} active</span></div>
          <div v-if="!activeOffers.length" class="rounded-3xl border border-dashed border-base-300 bg-base-100 p-12 text-center dark:border-white/10 dark:bg-[#0d2943]"><span class="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-base-200 text-slate-300 dark:bg-white/5"><Icon icon="lucide:inbox" width="22"/></span><p class="mt-3 text-sm font-bold text-slate-500 dark:text-white/40">No active incident offer right now.</p><p class="mt-1 text-xs text-slate-400">DASCARE will surface new eligible incidents here automatically.</p></div>
          <div v-else class="grid gap-4 xl:grid-cols-2"><article v-for="offer in activeOffers" :key="offer.id" class="overflow-hidden rounded-3xl border border-red-200 bg-base-100 shadow-sm dark:border-red-500/20 dark:bg-[#0d2943]"><div class="flex items-center justify-between bg-red-50 px-5 py-3 dark:bg-red-500/10"><span class="inline-flex items-center gap-2 text-xs font-black uppercase tracking-wider text-red-700 dark:text-red-300"><span class="h-2 w-2 animate-pulse rounded-full bg-red-500"></span>Response required</span><span class="font-mono text-sm font-black" :class="secondsLeft(offer)>20?'text-slate-700 dark:text-white/70':'text-red-600 dark:text-red-300'">{{ formatCountdown(offer) }}</span></div><div class="p-5"><div class="flex items-start justify-between gap-4"><div><p class="text-lg font-black text-slate-950 dark:text-white">{{offer.reference_number}}</p><p class="mt-1 text-sm font-bold text-slate-600 dark:text-white/55">{{offer.category_name}} · {{titleCase(offer.severity)}}</p></div><div class="rounded-xl bg-base-200 px-3 py-2 text-right"><p class="text-xl font-black text-slate-950 dark:text-white">{{Number(offer.total_score).toFixed(1)}}</p><p class="text-[0.62rem] uppercase tracking-wider text-slate-400">DSS score</p></div></div><div class="mt-4 grid gap-3 sm:grid-cols-2"><Info icon="lucide:map-pin" label="Location" :value="offer.address_text"/><Info icon="lucide:ambulance" label="Suggested unit" :value="`${offer.recommended_unit_code || 'Ready unit'} · ${titleCase(offer.recommended_ambulance_type || '')}`"/><Info icon="lucide:navigation" label="Estimated distance" :value="offer.distance_km!==null?`${Number(offer.distance_km).toFixed(1)} km`:'—'"/><Info icon="lucide:user-round" label="Requester" :value="offer.requester_name || 'Guest requester'"/></div><p class="mt-4 rounded-xl bg-base-200 p-3 text-xs leading-5 text-slate-500 dark:bg-white/[0.04] dark:text-white/45">{{offer.explanation}}</p><div class="mt-5 flex gap-3"><button :disabled="!canRespond||savingId===offer.id" class="flex-1 rounded-xl border border-base-300 px-4 py-2.5 text-sm font-bold text-slate-700 hover:bg-base-200 disabled:opacity-40 dark:border-white/10 dark:text-white/65" @click="openDecline(offer)">Decline</button><button :disabled="!canRespond||savingId===offer.id" class="flex-1 rounded-xl bg-red-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-red-700 disabled:opacity-40" @click="acceptOffer(offer)"><Icon v-if="savingId===offer.id" icon="lucide:loader-circle" width="15" class="mr-1 inline animate-spin"/>Accept Incident</button></div></div></article></div>
        </section>

        <section class="rounded-3xl border border-base-300 bg-base-100 shadow-sm dark:border-white/10 dark:bg-[#0d2943]"><div class="border-b border-base-300 px-5 py-4 dark:border-white/10"><h2 class="text-sm font-black text-slate-900 dark:text-white">Offer History</h2><p class="mt-1 text-xs text-slate-400">Accepted, declined, timed-out, and superseded offers.</p></div><div v-if="!historyOffers.length" class="p-10 text-center text-sm text-slate-400">No offer history yet.</div><div v-else class="divide-y divide-base-300 dark:divide-white/5"><div v-for="offer in historyOffers" :key="offer.id" class="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><div class="flex items-center gap-2"><p class="font-black text-slate-900 dark:text-white">{{offer.reference_number}}</p><span class="rounded-full px-2 py-0.5 text-[0.64rem] font-black uppercase" :class="statusClass(offer.offer_status)">{{titleCase(offer.offer_status)}}</span></div><p class="mt-1 text-xs text-slate-500 dark:text-white/40">{{offer.category_name}} · {{offer.barangay || 'Dasmariñas'}} · {{formatDate(offer.responded_at || offer.offered_at)}}</p><p v-if="offer.response_note" class="mt-1 text-xs text-slate-400">{{offer.response_note}}</p></div><span class="text-xs font-bold text-slate-400">DSS #{{offer.rank_position}} · {{Number(offer.total_score).toFixed(1)}}</span></div></div></section>
      </template>
    </div>

    <div v-if="declineOffer" class="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 px-4" @click.self="declineOffer=null"><form class="w-full max-w-md rounded-3xl border border-base-300 bg-base-100 p-6 shadow-2xl dark:border-white/10 dark:bg-[#071829]" @submit.prevent="confirmDecline"><h3 class="text-lg font-black text-slate-950 dark:text-white">Decline {{declineOffer.reference_number}}?</h3><p class="mt-2 text-sm text-slate-500 dark:text-white/45">DASCARE will immediately offer the incident to the next eligible organization. Add a concise operational reason.</p><textarea v-model.trim="declineNote" required maxlength="500" rows="4" class="mt-4 w-full resize-none rounded-xl border border-base-300 bg-base-200 p-3 text-sm outline-none focus:border-red-400 dark:border-white/10 dark:bg-white/[0.04] dark:text-white" placeholder="Example: No qualified crew currently available."></textarea><div class="mt-5 flex gap-3"><button type="button" class="flex-1 rounded-xl border border-base-300 px-4 py-2.5 text-sm font-bold dark:border-white/10" @click="declineOffer=null">Cancel</button><button type="submit" :disabled="savingId===declineOffer.id||!declineNote" class="flex-1 rounded-xl bg-red-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40">Decline & Escalate</button></div></form></div>
  </section>
</template>

<script setup>
import { computed, h, onMounted, onUnmounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { Icon } from '@iconify/vue'
import { fetchOrganizationOffers, respondToIncidentOffer } from '@/services/dispatchOperations'
import { useAlert } from '@/composables/useAlert'
import { useToast } from '@/composables/useToast'
import { useSession } from '@/composables/useSession'
import { useLiveUpdates } from '@/composables/useLiveUpdates'
import { realtimeChannels } from '@/services/realtime'
import LiveBadge from '@/components/realtime/LiveBadge.vue'

const alert=useAlert();const router=useRouter();const offers=ref([]);const stats=ref({});const loading=ref(false);const error=ref('');const canRespond=ref(false);const savingId=ref(null);const declineOffer=ref(null);const declineNote=ref('');const now=ref(Date.now());let tick=null
const activeOffers=computed(()=>offers.value.filter(o=>o.offer_status==='sent'))
const historyOffers=computed(()=>offers.value.filter(o=>o.offer_status!=='sent'))
const statCards=computed(()=>[
  {label:'Awaiting Response',value:stats.value.sent||0,icon:'lucide:inbox'},
  {label:'Accepted',value:stats.value.accepted||0,icon:'lucide:badge-check'},
  {label:'Declined',value:stats.value.declined||0,icon:'lucide:circle-x'},
  {label:'Timed Out',value:stats.value.timed_out||0,icon:'lucide:clock-alert'},
])
const Info={props:['icon','label','value'],setup(p){return()=>h('div',{class:'rounded-xl border border-base-300 p-3 dark:border-white/10'},[h('div',{class:'flex items-center gap-2 text-[0.65rem] font-bold uppercase tracking-wider text-slate-400'},[h(Icon,{icon:p.icon,width:13}),p.label]),h('p',{class:'mt-1 line-clamp-2 text-xs font-bold text-slate-700 dark:text-white/60'},p.value||'—')])}}
async function load(){loading.value=offers.value.length===0;error.value='';try{const data=await fetchOrganizationOffers();offers.value=data.offers;stats.value=data.stats;canRespond.value=!!data.can_respond}catch(e){error.value=e?.response?.data?.message||e.message||'Unable to load incident offers.'}finally{loading.value=false}}
async function acceptOffer(offer){const ok=await alert.confirm(`Accept ${offer.reference_number}? Your organization will take responsibility for the incident and proceed to resource assignment.`,'Accept incident');if(!ok)return;savingId.value=offer.id;try{const data=await respondToIncidentOffer(offer.id,'accept');alert.success(data.message);await load();router.push('/organization/assignments')}catch(e){alert.error(e?.response?.data?.message||e.message||'Unable to accept incident.')}finally{savingId.value=null}}
function openDecline(offer){declineOffer.value=offer;declineNote.value=''}
async function confirmDecline(){if(!declineOffer.value)return;savingId.value=declineOffer.value.id;try{const data=await respondToIncidentOffer(declineOffer.value.id,'decline',declineNote.value);alert.success(data.message);declineOffer.value=null;await load()}catch(e){alert.error(e?.response?.data?.message||e.message||'Unable to decline incident.')}finally{savingId.value=null}}
function secondsLeft(offer){return Math.max(0,Math.floor((new Date(String(offer.expires_at).replace(' ','T')).getTime()-now.value)/1000))}
function formatCountdown(offer){const s=secondsLeft(offer);return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function titleCase(v=''){return String(v).replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function formatDate(v){return v?new Date(String(v).replace(' ','T')).toLocaleString():'—'}
function statusClass(v){return {accepted:'bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-300',declined:'bg-red-50 text-red-700 dark:bg-red-500/10 dark:text-red-300',timed_out:'bg-slate-100 text-slate-600 dark:bg-white/5 dark:text-white/45',cancelled:'bg-slate-100 text-slate-500 dark:bg-white/5 dark:text-white/40'}[v]||'bg-base-200 text-slate-500'}
// Live updates: new/expired/answered offers arrive instantly (GPS pings on
// the org channel are ignored). Offers expire lazily on the server when a list
// loads (no cron), so this page also re-loads the moment a countdown hits 0 and
// keeps a 15 s poll — that is what hands an unanswered offer to the next org.
const toast=useToast();const { organization }=useSession()
const { live }=useLiveUpdates(load,{channels:()=>[realtimeChannels.value?.org],livePollMs:15000,onEvent:msg=>{if(msg.name==='ambulance.location')return false;if(msg.name==='offer.created'&&Number(msg.data?.organization_id)===Number(organization.value?.id))toast.info('A new incident offer needs a response.',{title:'New incident offer'})}})
const expiryReloaded=new Set()
function reloadOnExpiry(){const due=offers.value.some(o=>o.offer_status==='sent'&&secondsLeft(o)===0&&!expiryReloaded.has(o.id));if(!due)return;offers.value.forEach(o=>{if(o.offer_status==='sent'&&secondsLeft(o)===0)expiryReloaded.add(o.id)});setTimeout(load,1500)}
onMounted(()=>{load();tick=setInterval(()=>{now.value=Date.now();reloadOnExpiry()},1000)})
onUnmounted(()=>{clearInterval(tick)})
</script>
