<?php
require_once __DIR__ . '/../../cors.php';require_once __DIR__ . '/../../db/db.php';require_once __DIR__ . '/../../reusables/platform_guard.php';header('Content-Type: application/json');requirePlatformExecutive($pdo,'analytics.reports.read');
try{
 $stats=$pdo->query("SELECT (SELECT COUNT(*) FROM emergency_requests) incidents_total,(SELECT COUNT(*) FROM emergency_requests WHERE submitted_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)) incidents_30d,(SELECT COUNT(*) FROM emergency_requests WHERE status='completed') completed,(SELECT COUNT(*) FROM incident_offers WHERE offer_status='accepted') offers_accepted,(SELECT COUNT(*) FROM incident_offers WHERE offer_status='declined') offers_declined,(SELECT COUNT(*) FROM incident_offers WHERE offer_status='timed_out') offers_timed_out,(SELECT COUNT(*) FROM dispatch_assignments WHERE assignment_status NOT IN ('completed','cancelled','declined')) active_missions,(SELECT COUNT(*) FROM ambulances WHERE deleted_at IS NULL) fleet_total")->fetch(PDO::FETCH_ASSOC)?:[];
 $severity=$pdo->query("SELECT severity,COUNT(*) count FROM emergency_requests WHERE submitted_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY severity")->fetchAll(PDO::FETCH_ASSOC);
 $org=$pdo->query("SELECT o.name,COUNT(da.id) missions,SUM(da.assignment_status='completed') completed,ROUND(AVG(TIMESTAMPDIFF(MINUTE,da.assigned_at,da.arrived_at)),1) avg_response_minutes FROM organizations o LEFT JOIN dispatch_assignments da ON da.organization_id=o.id WHERE o.deleted_at IS NULL AND o.application_status='approved' GROUP BY o.id ORDER BY missions DESC,o.name LIMIT 10")->fetchAll(PDO::FETCH_ASSOC);
 $daily=$pdo->query("SELECT DATE(submitted_at) day,COUNT(*) count FROM emergency_requests WHERE submitted_at>=DATE_SUB(CURDATE(),INTERVAL 13 DAY) GROUP BY DATE(submitted_at) ORDER BY day")->fetchAll(PDO::FETCH_ASSOC);
 echo json_encode(['success'=>true,'stats'=>array_map('intval',$stats),'severity'=>$severity,'organizations'=>$org,'daily'=>$daily]);
}catch(Throwable $e){error_log('Platform analytics failed: '.$e->getMessage());platformJsonError(500,'Unable to load platform analytics.');}
