<?php
require_once __DIR__ . '/../../../cors.php';
require_once __DIR__ . '/../../../db/db.php';
require_once __DIR__ . '/../../../reusables/organization_rbac.php';
require_once __DIR__ . '/../../../reusables/assignment_helpers.php';
require_once __DIR__ . '/../../../reusables/fleet_helpers.php';
require_once __DIR__ . '/../../../reusables/push.php';
header('Content-Type: application/json');
if(($_SERVER['REQUEST_METHOD']??'GET')!=='POST') organizationJsonError(405,'Method not allowed.');
$ctx=requireOrganizationAccess($pdo,null);$body=json_decode(file_get_contents('php://input'),true)?:[];$id=(int)($body['assignment_id']??0);$next=strtolower(trim((string)($body['status']??'')));$note=mb_substr(trim(strip_tags((string)($body['note']??''))),0,500);
if($id<=0) organizationJsonError(422,'Choose a mission.');
$allowed=['acknowledged','responding','on_scene','transporting','completed'];if(!in_array($next,$allowed,true)) organizationJsonError(422,'Invalid mission status.');
try{
 $pdo->beginTransaction();
 $stmt=$pdo->prepare("SELECT da.*,er.status request_status,er.reference_number,er.requester_user_id,a.status ambulance_status,a.unit_code FROM dispatch_assignments da JOIN emergency_requests er ON er.id=da.emergency_request_id JOIN ambulances a ON a.id=da.ambulance_id WHERE da.id=? AND da.organization_id=? LIMIT 1 FOR UPDATE");$stmt->execute([$id,$ctx['organization_id']]);$m=$stmt->fetch(PDO::FETCH_ASSOC);if(!$m)throw new RuntimeException('Mission not found.');
 $isDispatcher=($ctx['user_role']==='organization_admin')||organizationHasPermission($pdo,$ctx,'dispatch.dispatch_assignments.update');$hasMission=($ctx['user_role']==='organization_admin')||organizationHasPermission($pdo,$ctx,'dispatch.mission_status.update');
 if(!$isDispatcher&&!$hasMission)throw new RuntimeException('You do not have permission to update mission status.');
 if(!$isDispatcher){$crew=$pdo->prepare('SELECT 1 FROM crew_assignments WHERE dispatch_assignment_id=? AND organization_member_id=? LIMIT 1');$crew->execute([$id,$ctx['organization_member_id']]);if(!$crew->fetchColumn())throw new RuntimeException('Only assigned responders can update this mission.');}
 $trans=['assigned'=>['acknowledged'],'acknowledged'=>['responding'],'responding'=>['on_scene'],'on_scene'=>['transporting','completed'],'transporting'=>['completed']];$old=$m['assignment_status'];if(!in_array($next,$trans[$old]??[],true))throw new RuntimeException('That mission transition is not allowed from the current status.');
 if($old==='transporting'&&$next==='completed'){ $handoff=$pdo->prepare("SELECT 1 FROM patient_handoffs WHERE dispatch_assignment_id=? AND status='completed' LIMIT 1"); $handoff->execute([$id]); if(!$handoff->fetchColumn()) throw new RuntimeException('Complete the receiving-facility handoff before closing a transporting mission.'); }
 $timeCols=['acknowledged'=>'acknowledged_at','responding'=>'departed_at','on_scene'=>'arrived_at','completed'=>'completed_at'];$sets=['assignment_status=?'];$params=[$next];if(isset($timeCols[$next])){$sets[]=$timeCols[$next].'=NOW()';}$params[]=$id;$pdo->prepare('UPDATE dispatch_assignments SET '.implode(',',$sets).' WHERE id=?')->execute($params);
 $requestSets=['status=?'];$rp=[$next];$reqTime=['acknowledged'=>'acknowledged_at','on_scene'=>'arrived_at','transporting'=>'transport_started_at','completed'=>'completed_at'];if(isset($reqTime[$next]))$requestSets[]=$reqTime[$next].'=NOW()';$rp[]=$m['emergency_request_id'];$pdo->prepare('UPDATE emergency_requests SET '.implode(',',$requestSets).' WHERE id=?')->execute($rp);
 $ambMap=['acknowledged'=>'reserved','responding'=>'dispatched','on_scene'=>'on_scene','transporting'=>'transporting','completed'=>'returning'];$newAmb=$ambMap[$next];if($newAmb!==$m['ambulance_status']){$pdo->prepare('UPDATE ambulances SET status=? WHERE id=?')->execute([$newAmb,$m['ambulance_id']]);fleetStatusLog($pdo,(int)$m['ambulance_id'],$m['ambulance_status'],$newAmb,(int)$ctx['user_id'],'Mission '.$m['reference_number'].' → '.$next.'.');}
 $labels=['acknowledged'=>'Mission acknowledged by response team.','responding'=>'Ambulance departed and is responding to the scene.','on_scene'=>'Response team arrived on scene.','transporting'=>'Patient transport started.','completed'=>'Mission completed.'];
 assignmentLog($pdo,$id,$old,$next,(int)$ctx['user_id'],$note?:$labels[$next]);$pdo->prepare('INSERT INTO emergency_request_status_logs (emergency_request_id,old_status,new_status,changed_by_user_id,notes) VALUES (?,?,?,?,?)')->execute([$m['emergency_request_id'],$m['request_status'],$next,(int)$ctx['user_id'],$note?:$labels[$next]]);
 if($next==='acknowledged'){$pdo->prepare("UPDATE crew_assignments SET response_status='acknowledged',acknowledged_at=COALESCE(acknowledged_at,NOW()) WHERE dispatch_assignment_id=? AND organization_member_id=?")->execute([$id,$ctx['organization_member_id']]);}
 if($next==='completed'){$members=$pdo->prepare('SELECT organization_member_id FROM crew_assignments WHERE dispatch_assignment_id=?');$members->execute([$id]);$mids=array_map('intval',$members->fetchAll(PDO::FETCH_COLUMN));$pdo->prepare("UPDATE crew_assignments SET response_status='completed' WHERE dispatch_assignment_id=?")->execute([$id]);$up=$pdo->prepare("UPDATE personnel_profiles SET availability_status='available' WHERE organization_member_id=? AND availability_status='assigned'");$log=$pdo->prepare("INSERT INTO personnel_availability_logs (organization_member_id,old_status,new_status,changed_by_user_id,notes) VALUES (?,'assigned','available',?,?)");foreach($mids as $mid){$up->execute([$mid]);if($up->rowCount())$log->execute([$mid,(int)$ctx['user_id'],'Released after '.$m['reference_number'].'.']);}}
 if(!empty($m['requester_user_id'])){$titles=['acknowledged'=>'Response Team Acknowledged','responding'=>'Ambulance En Route','on_scene'=>'Responders Arrived','transporting'=>'Patient Transport Started','completed'=>'Rescue Mission Completed'];assignmentNotifyUser($pdo,(int)$m['requester_user_id'],'dispatch_update',$titles[$next],$labels[$next].' Reference: '.$m['reference_number'].'.','emergency_request',(int)$m['emergency_request_id'],'mission-status:'.$id.':'.$next);}
 // DASCARE app (no-op without Firebase): guest phones and linked (dedup) reports following this incident.
 $pushTitles=['acknowledged'=>'Response Team Acknowledged','responding'=>'Ambulance En Route','on_scene'=>'Responders Arrived','transporting'=>'Patient Transport Started','completed'=>'Rescue Mission Completed'];if(isset($pushTitles[$next]))pushQueueRequestFollowers($pdo,(int)$m['emergency_request_id'],$pushTitles[$next],$labels[$next].' Reference: '.$m['reference_number'].'.',$next);
 $audit=$pdo->prepare("INSERT INTO audit_logs (user_id,organization_id,action,entity_type,entity_id,old_values,new_values,ip_address,user_agent) VALUES (?,?, 'dispatch.mission_status','dispatch_assignment',?,?,?,?,?)");$audit->execute([(int)$ctx['user_id'],(int)$ctx['organization_id'],$id,json_encode(['status'=>$old]),json_encode(['status'=>$next,'note'=>$note]),$_SERVER['REMOTE_ADDR']??null,mb_substr((string)($_SERVER['HTTP_USER_AGENT']??''),0,255)]);
 $pdo->commit();echo json_encode(['success'=>true,'message'=>$labels[$next]]);
}catch(RuntimeException $e){if($pdo->inTransaction())$pdo->rollBack();organizationJsonError(409,$e->getMessage());}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('Mission status failed: '.$e->getMessage());organizationJsonError(500,'Unable to update mission status.');}
