<?php
require_once __DIR__ . '/../../cors.php';require_once __DIR__ . '/../../db/db.php';require_once __DIR__ . '/../../reusables/platform_guard.php';header('Content-Type: application/json');requirePlatformExecutive($pdo,'organizations.org_documents.read');
$days=max(1,min(365,(int)($_GET['warning_days']??30)));
try{
 $orgs=$pdo->query("SELECT o.id,o.name,o.status,(SELECT COUNT(*) FROM organization_documents d WHERE d.organization_id=o.id) docs_total,(SELECT COUNT(*) FROM organization_documents d WHERE d.organization_id=o.id AND d.status='pending') docs_pending,(SELECT COUNT(*) FROM organization_documents d WHERE d.organization_id=o.id AND d.status='rejected') docs_rejected,(SELECT COUNT(*) FROM ambulances a WHERE a.organization_id=o.id AND a.deleted_at IS NULL) fleet_total,(SELECT COUNT(*) FROM ambulances a WHERE a.organization_id=o.id AND a.deleted_at IS NULL AND ((a.registration_expiry IS NOT NULL AND a.registration_expiry < CURDATE()) OR (a.inspection_expiry IS NOT NULL AND a.inspection_expiry < CURDATE()))) expired_units FROM organizations o WHERE o.deleted_at IS NULL AND o.application_status='approved' ORDER BY o.name")->fetchAll(PDO::FETCH_ASSOC);
 $docs=$pdo->query("SELECT d.id,d.organization_id,o.name organization_name,d.doc_type,d.original_name,d.status,d.rejection_reason,d.reviewed_at,d.created_at FROM organization_documents d JOIN organizations o ON o.id=d.organization_id WHERE o.deleted_at IS NULL ORDER BY (d.status='pending') DESC,d.created_at DESC LIMIT 100")->fetchAll(PDO::FETCH_ASSOC);
 $exp=$pdo->query("SELECT a.id,a.unit_code,a.plate_number,a.registration_expiry,a.inspection_expiry,o.name organization_name FROM ambulances a JOIN organizations o ON o.id=a.organization_id WHERE a.deleted_at IS NULL AND o.deleted_at IS NULL AND ((a.registration_expiry IS NOT NULL AND a.registration_expiry <= DATE_ADD(CURDATE(),INTERVAL $days DAY)) OR (a.inspection_expiry IS NOT NULL AND a.inspection_expiry <= DATE_ADD(CURDATE(),INTERVAL $days DAY))) ORDER BY LEAST(COALESCE(a.registration_expiry,'2999-12-31'),COALESCE(a.inspection_expiry,'2999-12-31')) LIMIT 100")->fetchAll(PDO::FETCH_ASSOC);
 echo json_encode(['success'=>true,'organizations'=>$orgs,'documents'=>$docs,'credential_alerts'=>$exp,'stats'=>['organizations'=>count($orgs),'pending_documents'=>array_sum(array_map(fn($x)=>(int)$x['docs_pending'],$orgs)),'rejected_documents'=>array_sum(array_map(fn($x)=>(int)$x['docs_rejected'],$orgs)),'credential_alerts'=>count($exp)]]);
}catch(Throwable $e){error_log('Platform compliance failed: '.$e->getMessage());platformJsonError(500,'Unable to load compliance overview.');}
